/**
 * Scans src/assets/ and generates registry.ts with static require() calls.
 * Run: npm run generate-registry
 */
import * as fs from 'fs';
import * as path from 'path';

const ASSETS_DIR = path.join(__dirname, '..', 'src', 'assets');
const OUTPUT_FILE = path.join(ASSETS_DIR, 'registry.ts');
const EXTENSIONS = ['.png', '.jpg', '.jpeg', '.json', '.mp3', '.aac', '.wav'];

function scanDir(dir: string, base: string): string[] {
  const entries: string[] = [];
  const items = fs.readdirSync(dir, { withFileTypes: true });

  for (const item of items) {
    if (item.name === 'registry.ts') continue;
    const fullPath = path.join(dir, item.name);
    const relativePath = path.relative(base, fullPath);

    if (item.isDirectory()) {
      entries.push(...scanDir(fullPath, base));
    } else if (EXTENSIONS.includes(path.extname(item.name).toLowerCase())) {
      entries.push(relativePath);
    }
  }
  return entries;
}

const files = scanDir(ASSETS_DIR, ASSETS_DIR).sort();

const lines = [
  '/**',
  ' * AUTO-GENERATED by scripts/generate-asset-registry.ts',
  ' * Do not edit manually. Run: npm run generate-registry',
  ' */',
  '',
  'const AssetRegistry: Record<string, any> = {',
  ...files.map((f) => `  '${f}': require('./${f}'),`),
  '};',
  '',
  'export function resolveAsset(path: string): any {',
  '  const asset = AssetRegistry[path];',
  '  if (!asset) {',
  "    console.warn(`[AssetRegistry] Asset not found: ${path}`);",
  '    return null;',
  '  }',
  '  return asset;',
  '}',
  '',
  'export default AssetRegistry;',
  '',
];

fs.writeFileSync(OUTPUT_FILE, lines.join('\n'));
console.log(`Generated registry with ${files.length} assets → ${OUTPUT_FILE}`);
